### ISSUE TITLE
Duplicate and resolve pre-processing error that led to 5% failure rate during LBL study.

### ISSUE THREAD

**Issue by praftery** [CenterForTheBuiltEnvironment/mave-app#15]

**Comment by praftery** [comment]
See example file that causes this issue (from Samir at LBL) - seems due to values being parsed as integers and subsequent float NaN mismatch. See error:

Processing input file ===
-- Missing datetime interval between 2012-11-04 07:45:00 and 2012-11-04 09:00:00
Traceback (most recent call last):
  File "bpe.py", line 548, in <module>
    bpe(**args.**dict**)
  File "bpe.py", line 318, in bpe
    X, y, headers, train_datetimes, force_month = process_input_data(f)
  File "bpe.py", line 200, in process_input_data
    new_row = np.array([(new_dt,) + (np.nan,) \* (row_length - 1)], dtype=arr.dtype)
ValueError: cannot convert float NaN to integer
